[build]

rustflags = [
    "-Wmissing_debug_implementations",
    "-Wclippy::all",
    "-Wclippy::dbg_macro",
    "-Wclippy::type_complexity",
    "-Wclippy::todo",
    "-Wclippy::empty_enum",
    "-Wclippy::enum_glob_use",
    "-Wclippy::mem_forget",
    "-Wclippy::unused_self",
    "-Wclippy::filter_map_next",
    "-Wclippy::needless_continue",
    "-Wclippy::needless_borrow",
    "-Wclippy::match_wildcard_for_single_variants",
    "-Wclippy::if_let_mutex",
    "-Wclippy::mismatched_target_os",
    "-Wclippy::await_holding_lock",
    "-Wclippy::match_on_vec_items",
    "-Wclippy::imprecise_flops",
    "-Wclippy::suboptimal_flops",
    "-Wclippy::lossy_float_literal",
    "-Wclippy::rest_pat_in_fully_bound_structs",
    "-Wclippy::fn_params_excessive_bools",
    "-Wclippy::exit",
    "-Wclippy::inefficient_to_string",
    "-Wclippy::linkedlist",
    "-Wclippy::macro_use_imports",
    "-Wclippy::option_option",
    "-Wclippy::verbose_file_reads",
    "-Wclippy::unnested_or_patterns",
    "-Wclippy::str_to_string",
    "-Wrust_2018_idioms",
    "-Wfuture_incompatible",
    "-Wnonstandard_style",
    "-Wmissing_debug_implementations",
    # "-Wmissing_docs",
    "-Dunreachable_pub",
    "-Dprivate_interfaces",
]
